### ISSUE TITLE
Some errors with lua

### ISSUE THREAD

**Issue by TheSuperPlayer** [StoneLineDevTeam/UMod#10]
When i am trying to open the newest version in the editor it gives me the following:

```
[2016.04.04-01.29.04:341][  0]C:\Users\Documents\Unreal Projects\UMod-UMod_Alpha\Source\UMod\Lua\LuaInterface.cpp(318): error C3861: 'luaL_register': identifier not found
[2016.04.04-01.29.04:341][  0]C\Users\Documents\Unreal Projects\UMod-UMod_Alpha\Source\UMod\Lua\LuaInterface.cpp(320): error C3861: 'luaL_register': identifier not found
[2016.04.04-01.29.04:442][  0]C:\Users\Documents\Unreal Projects\UMod-UMod_Alpha\Source\UMod\Lua\LuaEntityBase.cpp(27): error C2664: 'void LuaInterface::Register(FString *,const luaL_Reg *)': cannot convert argument 1 from 'const char [7]' to 'FString *'
[2016.04.04-01.29.04:442][  0]C:\Users\Documents\Unreal Projects\UMod-UMod_Alpha\Source\UMod\Lua\LuaEntityBase.cpp(27): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
[2016.04.04-01.29.04:544][  0]-------- End Detailed Actions Stats -----------------------------------------------------------
[2016.04.04-01.29.04:544][  0]ERROR: UBT ERROR: Failed to produce item: C:\Users\Documents\Unreal Projects\UMod-UMod_Alpha\Binaries\Win64\UE4Editor-UMod.dll
```

And with the previous version it compiled the project fine but when i tried to launch it Windows gave me and error saying that lua53.dll is not installed on my computer. But i have the lua53.dll file in the Binary folder? Is there something lua related i have to install first?

SuperPlayer

**Comment by Yuri6037** [comment]
You downloaded the non building version... I tried to implement new functions to LuaInterface yesterday and I broke the game sorry for the incoveniance. But don't worry I'm preparing for EntityBase integration.
I'll give you LuaInterface with UserData support and I'll prepare a few methods to complete (inside LuaEntityBase)

**Comment by Yuri6037** [comment]
I'll update the project for Editor version 4.10.4

**Comment by Yuri6037** [comment]
Well we have a problem, after updating to 4.10.4 I can no longer compile the game : Application.ico is missing !

**Comment by Yuri6037** [comment]
Here we go issue fixed, you can now start implementing PushEntity.
Basicaly the idea is to pass a table which will contain the lua entity table (if any) as metatble, which has as metatable the entitybase's metatable. And then in the first created table put a __self value set to a userdata which will contain the pointer to AEntityBase. And finaly create a lua reference of that table and store this reference in AEntityBase for a later push if nessessary.
This of course does not support for inheritance, this only supports prototyping.

If you know a better way just let me know.
